In [16]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementNotVisibleException, SessionNotCreatedException

# Importing required Classes
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException
from selenium.common.exceptions import ElementNotInteractableException

#Importing requests
import requests

# importing regex
import re


import urllib.request
from selenium.webdriver.chrome.options import Options
import time

In [2]:
driver = webdriver.Chrome(r'H:/downloads/chromedriver_win32/chromedriver.exe')

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/4119202291.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r'H:/downloads/chromedriver_win32/chromedriver.exe')

1. Scrape the details of most viewed videos on YouTube from Wikipedia:
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/
You need to find following details:

A) Rank

B) Name

C) Artist

D) Upload date

E) Views

In [7]:
def most_viewed_videos_wiki(url):

    opts = Options()

    url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"

    opts.add_argument("user-agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36")

    driver.get(url)

    driver.find_element_by_xpath("//b").click()

    time.sleep(3)

    records = []
    for row in driver.find_elements_by_xpath("(//table[@class='wikitable sortable jquery-tablesorter'])[1]//tr")[1:-1]:
        temp = ''
        for element in row.find_elements_by_xpath(".//td"):        
            temp += element.text + '|'
        records.append(temp.split('|')[:-2])

    df = pd.DataFrame(records,columns=['rank','video_name','artist','date_uploaded','views(M)'])
    
    arranged_cols = ['rank','video_name','artist','date_uploaded','views(M)']
    
    df.video_name = df.video_name.apply(lambda x:x[:-4].strip('"'))
    df = df[arranged_cols]

    return df


most_viewed_videos_wiki("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

C:\Users\USER\AppData\Local\Temp/ipykernel_10588/1369906942.py:11: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  driver.find_element_by_xpath("//b").click()
C:\Users\USER\AppData\Local\Temp/ipykernel_10588/1369906942.py:16: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for row in driver.find_elements_by_xpath("(//table[@class='wikitable sortable jquery-tablesorter'])[1]//tr")[1:-1]:
C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py:426: UserWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  warnings.warn("find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead")

,rank,video_name,artist,date_uploaded,views(M)
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,10.48,"June 17, 2016"
1,2.,Despacito,Luis Fonsi,7.81,"January 12, 2017"
2,3.,Johny Johny Yes Papa,LooLoo Kids,6.28,"October 8, 2016"
3,4.,Shape of You,Ed Sheeran,5.68,"January 30, 2017"
4,5.,See You Again,Wiz Khalifa,5.47,"April 6, 2015"
5,6.,Bath Song,Cocomelon – Nursery Rhymes,5.23,"May 2, 2018"
6,7.,Phonics Song with Two Words,ChuChu TV,4.56,"March 6, 2014"
7,8.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,4.56,"February 27, 2018"
8,9.,Uptown Funk,Mark Ronson,4.53,"November 19, 2014"
9,10.,Masha and the Bear – Recipe for Disaster,Get Movies,4.49,"January 31, 2012"
10,11.,Gangnam Style,Psy,4.39,"July 15, 2012"
11,12.,Wheels on the Bus,Cocomelon – Nursery Rhymes,3.92,"May 24, 2018"
12,13.,Dame Tu Cosita,El Chombo,3.92,"April 5, 2018"
13,14.,Sugar,Maroon 5,3.68,"January 14, 2015"
14,15.,Roar,Katy Perry,3.56,"September 5, 2013"
15,16.,Counting Stars,OneRepublic,3.55,"May 31, 2013"
16,17.,Sorry,Justin Bieber,3.53,"October 22, 2015"
17,18.,Thinking Out Loud,Ed Sheeran,3.43,"October 7, 2014"
18,19.,Axel F,Crazy Frog,3.31,"June 16, 2009"
19,20.,Girls Like You,Maroon 5,3.27,"May 31, 2018"
20,21.,Faded,Alan Walker,3.26,"December 3, 2015"
21,22.,Dark Horse,Katy Perry,3.25,"February 20, 2014"
22,23.,Let Her Go,Passenger,3.21,"July 25, 2012"
23,24.,Baa Baa Black Sheep,Cocomelon – Nursery Rhymes,3.21,"June 25, 2018"
24,25.,Bailando,Enrique Iglesias,3.19,"April 11, 2014"
25,26.,Lean On,Major Lazer,3.19,"March 22, 2015"
26,27.,Shake It Off,Taylor Swift,3.16,"August 18, 2014"
27,28.,Perfect,Ed Sheeran,3.14,"November 9, 2017"
28,29.,Waka Waka (This Time for Africa),Shakira,3.11,"June 4, 2010"
29,30.,Mi Gente,J Balvin,3.06,"June 29, 2017"

2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.

You need to find following details:

A) Match title (I.e. 1st ODI)

B) Series

C) Place

D) Date

E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [6]:
url='https://www.bcci.tv'
driver.get(url)

search_btn=driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul[1]/li[2]/a')
search_btn
search_btn.click()

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3924481329.py:4: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  search_btn=driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul[1]/li[2]/a')

In [7]:
Match=driver.find_elements_by_xpath('//span[@class="matchOrderText ng-binding ng-scope"]')
len(Match)

Match_title=[]
for i in Match:
    Match_title.append(i.text);
Match_title

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1708401398.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  Match=driver.find_elements_by_xpath('//span[@class="matchOrderText ng-binding ng-scope"]')

['1st T20I -', '2nd T20I -', '3rd T20I -', '4th T20I -', '5th T20I -']

In [8]:
Series_1=driver.find_elements_by_xpath('//div[@class="fixture-tab-inner row"]/div/div/div[1]/h5[2]/span')
len(Series_1)

Series=[]
for j in Series_1:
    Series.append(j.text)
Series

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/4105169149.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  Series_1=driver.find_elements_by_xpath('//div[@class="fixture-tab-inner row"]/div/div/div[1]/h5[2]/span')

['SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022',
 'SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022',
 'SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022',
 'SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022',
 'SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022']

In [9]:
place=driver.find_elements_by_xpath('//span[@class="ng-binding ng-scope"]')
len(place)

Place=[]
for k in place:
    Place.append(k.text)
Place

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1532483022.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  place=driver.find_elements_by_xpath('//span[@class="ng-binding ng-scope"]')

['Arun Jaitley Stadium,',
 'Barabati Stadium,',
 'Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium,',
 'Saurashtra Cricket Association Stadium,',
 'M Chinnaswamy Stadium,']

In [10]:
date=driver.find_elements_by_xpath('//div[@class="fixture-tab-inner row"]/div/div/div[1]/div/div[1]/h5')
len(date)


Date=[]
for k in date:
    Date.append(k.text)
Date

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/932616685.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  date=driver.find_elements_by_xpath('//div[@class="fixture-tab-inner row"]/div/div/div[1]/div/div[1]/h5')

['9 JUN 2022', '12 JUN 2022', '14 JUN 2022', '17 JUN 2022', '19 JUN 2022']

In [11]:
time=driver.find_elements_by_xpath('//div[@class="fixture-tab-inner row"]/div/div/div[1]/div/div[2]/h5')
len(time)

Time=[]
for k in time:
    Time.append(k.text)
Time

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/563645699.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  time=driver.find_elements_by_xpath('//div[@class="fixture-tab-inner row"]/div/div/div[1]/div/div[2]/h5')

['7:30 PM IST', '7:30 PM IST', '7:30 PM IST', '7:30 PM IST', '7:30 PM IST']

In [12]:
BCCI=pd.DataFrame()
BCCI['Match_title']= Match_title
BCCI['Series']= Series
BCCI['Place ']= Place
BCCI['Time']= Time
BCCI

,Match_title,Series,Place,Time
0,1st T20I -,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Arun Jaitley Stadium,",7:30 PM IST
1,2nd T20I -,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Barabati Stadium,",7:30 PM IST
2,3rd T20I -,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium,",7:30 PM IST
3,4th T20I -,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Saurashtra Cricket Association Stadium,",7:30 PM IST
4,5th T20I -,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"M Chinnaswamy Stadium,",7:30 PM IST

3. Scrape the details of selenium exception from guru99.com.¶
Url = https://www.guru99.com/

You need to find following details:

A) Name

B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code

In [12]:
def guru_sel_exc_handling(url):
    opts = Options()
    

    opts.add_argument("user-agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36")


    driver.get(url)

    driver.find_element_by_xpath("//a[@title='Selenium']").click()

    driver.find_element_by_xpath("//a[contains(@title,'Selenium Exception Handling')]").click()

    col_names,expn_l,des_l = [],[],[]

    for n,elements in enumerate(driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/*/td")):

        if n%2 == 0:
            if n == 0:
                col_names.append(elements.text)
            else:
                expn_l.append(elements.text)

        if n%2 == 1:
            if n == 1:
                col_names.append(elements.text)
            else:
                des_l.append(elements.text)

    df = pd.DataFrame(list(zip(expn_l,des_l)),columns=col_names) 

    return df

guru_sel_exc_handling("https://www.guru99.com/")

C:\Users\USER\AppData\Local\Temp/ipykernel_10588/676845359.py:10: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  driver.find_element_by_xpath("//a[@title='Selenium']").click()
C:\Users\USER\AppData\Local\Temp/ipykernel_10588/676845359.py:12: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  driver.find_element_by_xpath("//a[contains(@title,'Selenium Exception Handling')]").click()
C:\Users\USER\AppData\Local\Temp/ipykernel_10588/676845359.py:16: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for n,elements in enumerate(driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/*/td")):

,ElementNotVisibleException,This type of Selenium exception occurs when an existing element in DOM has a feature set as hidden.
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/

You have to find following details:

A) Rank

B) State

C) GSDP(18-19)

D) GSDP(17-18)

E) Share(2017)

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code

In [19]:
# Opening Wikipedia webpage
url='https://www.statisticstimes.com/'
driver.get(url)
time.sleep(1)


# Creating Empty lists

Rank =[]
State =[]
GDSP_19_20=[]
GDSP_18_19 =[]
Share =[]
GDP =[]

In [20]:
# Clicking on India under ecomony section
India=driver.find_element_by_xpath('//div[@class="dropdown"][2]/div/a[3]')
try:
    India.click()
except ElementNotInteractableException:
    driver.get(India.get_attribute('href'))
# Clicking Indian State GDP
state = driver.find_element_by_xpath('//ul[@style="list-style-type:none;margin-left:20px;"]/li[1]/a')
try:
    state.click()
except ElementNotInteractableException:
    driver.get(state.get_attribute('href'))
time.sleep(2)
try:
    rank=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[1]')
    for i in rank:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append('NA')
len(Rank)

# Extracting state name via Xpath
try:
    state=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[2]')
    for i in state:
        State.append(i.text)
except NoSuchElementException:
    State.append('NA')
len(state)

# Extracting GDSP 19-20 via Xpath
try:
    gdsp_19_20=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[3]')
    for i in gdsp_19_20:
        GDSP_19_20.append(i.text)
except NoSuchElementException:
    GDSP_19_20.append('NA')
len(GDSP_19_20)

# Extracting GDSP 18-19 via Xpath
try:
    gdsp_18_19=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[4]')
    for i in gdsp_18_19:
        GDSP_18_19.append(i.text)
except NoSuchElementException:
    GDSP_18_19.append('NA')
len(GDSP_18_19)

# Extracting share in billons via Xpath
try:
    share=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[5]')
    for i in share:
        Share.append(i.text)
except NoSuchElementException:
    Share.append('NA')
len(share)

# Extracting GDP via Xpath
try:
    gdp=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[6]')
    for i in gdp:
        GDP.append(i.text)
except NoSuchElementException:
    GDP.append('NA')
len(GDP)

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3717221831.py:2: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  India=driver.find_element_by_xpath('//div[@class="dropdown"][2]/div/a[3]')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3717221831.py:8: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  state = driver.find_element_by_xpath('//ul[@style="list-style-type:none;margin-left:20px;"]/li[1]/a')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3717221831.py:15: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  rank=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[1]')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3717221831.py:24: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  state=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[2]')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3717221831.py:33: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  gdsp_19_20=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[3]')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3717221831.py:42: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  gdsp_18_19=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[4]')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3717221831.py:51: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  share=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[5]')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3717221831.py:60: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  gdp=driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[6]')

33

In [21]:
# Dataframe for scrap data
Statewise_GDP=pd.DataFrame({'Rank':Rank,'State':State,'GDSP 19-20':GDSP_19_20,'GDSP 18-19':GDSP_18_19,
                            'Share':Share,'GDP (in Billions)':GDP})
print('\033[1m'+'State-wise GDP of India :'+'\033[0m')
Statewise_GDP

State-wise GDP of India :

,Rank,State,GDSP 19-20,GDSP 18-19,Share,GDP (in Billions)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/

You have to find the following details:

A) Repository title

B) Repository description

C) Contributors count

D) Language used

In [22]:
# Opening Wikipedia webpage
url='https://github.com/'
driver.get(url)
time.sleep(1)
explore = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary")
explore.click()
time.sleep(2)
# Clicking on trending option
trending=driver.find_element_by_xpath('html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a')
try:
    trending.click()
except ElementNotInteractableException:
    driver.get(trending.get_attribute('href'))
# Empty list
Repository = []
Repository_des = []
Contributors = []
Language = []
try: # Scraping repository
    for i in driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a"):
        Repository.append(i.text)
except NoSuchElementException as e:
    Repository.append('NA')
try: # Scraping Repository description
    for i in driver.find_elements_by_xpath("//p[@class='col-9 color-fg-muted my-1 pr-4']"):
        Repository_des.append(i.text)
except NoSuchElementException as e:
    Repository_des.append('NA')
try: # Scraping Contributors count
    for i in driver.find_elements_by_xpath("//*[@id='js-pjax-container']/div[3]/div/div[2]/article/div[2]/a[2]"):
        Contributors.append(i.text)
except NoSuchElementException as e:
    Contributors.append('NA')
try: # Scraping language
    for i in driver.find_elements_by_xpath("//span[@class='d-inline-block ml-0 mr-3']"):
        Language.append(i.text)
        
except NoSuchElementException as e:
    Language.append('NA')
len(Language),len(Repository),len(Repository_des),len(Contributors)

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1150935024.py:5: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  explore = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary")
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1150935024.py:9: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  trending=driver.find_element_by_xpath('html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1150935024.py:20: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a"):
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1150935024.py:25: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//p[@class='col-9 color-fg-muted my-1 pr-4']"):
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1150935024.py:30: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//*[@id='js-pjax-container']/div[3]/div/div[2]/article/div[2]/a[2]"):
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1150935024.py:35: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//span[@class='d-inline-block ml-0 mr-3']"):

(22, 25, 24, 25)

In [25]:
import numpy as np
trending=pd.DataFrame()
trending['Repository_title']= pd.Series(Repository)
trending['Repository_description']= pd.Series(Repository_des)
trending['Contributors_count']= pd.Series(Contributors)
trending['Language_Used']=pd.Series(Language)
trending

,Repository_title,Repository_description,Contributors_count,Language_Used
0,pyscript / pyscript,叮咚买菜助手，使用iOS客户端原生API，支持高峰期下单、支持捡漏、支持多账号、支持webh...,120,JavaScript
1,Runc2333 / dingdong-helper-node,Papers from the computer science community to ...,32,JavaScript
2,papers-we-love / papers-we-love,A complete computer science study plan to beco...,"4,722",Shell
3,jwasham / coding-interview-university,A local-first personal finance system,"59,290",JavaScript
4,actualbudget / actual,Actual's server,249,JavaScript
5,actualbudget / actual-server,"Code Repository for The Kaggle Book, Published...",121,Jupyter Notebook
6,PacktPublishing / The-Kaggle-Book,Fig adds autocomplete to your terminal.,86,TypeScript
7,withfig / autocomplete,A libre lightweight streaming front-end for An...,"3,940",Java
8,TeamNewPipe / NewPipe,"Low code project to build admin panels, intern...","2,277",TypeScript
9,appsmithorg / appsmith,Aria/qBittorrent Telegram mirror/leech bot,"1,338",Python
10,anasty17 / mirror-leech-telegram-bot,Combined Resource Folder from Multiple Sources...,"2,793",Lua
11,Koko-boya / Grasscutter_Resources,"Implementation of DALL-E 2, OpenAI's updated t...",39,Python
12,lucidrains / DALLE2-pytorch,freeCodeCamp.org's open-source codebase and cu...,165,TypeScript
13,freeCodeCamp / freeCodeCamp,play meeeeee,"28,545",JavaScript
14,Code-Bullet / Jump-King,AWESOME-Azure-Architecture,17,Python
15,lukemurraynz / awesome-azure-architecture,Learn how to design large-scale systems. Prep ...,79,JavaScript
16,donnemartin / system-design-primer,💯 Curated interview preparation materials for ...,"32,545",C
17,yangshun / tech-interview-handbook,A new bootable USB solution.,"9,612",JavaScript
18,ventoy / Ventoy,The open-source repo for docs.github.com,"2,550",C++
19,github / docs,Bitcoin Core integration/staging tree,"51,302",Python
20,bitcoin / bitcoin,🔒 Consolidating and extending hosts files from...,"32,283",Java
21,StevenBlack / hosts,收集整理 GitHub 上高质量、有趣的开源项目。,"1,809",HTML
22,Wechat-ggGitHub / Awesome-GitHub-Repo,A server software reimplementation for a certa...,444,NaN
23,Grasscutters / Grasscutter,美国大学备考资料 How to apply US colleges,"1,380",NaN
24,F4bwDP6a6W / FLY_US,NaN,712,NaN

6. Scrape the details of top 100 songs on billboard.com.
Url = https://www.billboard.com/

You have to find the following details:

A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code

In [27]:
url='https:/www.billboard.com/'
driver.get(url)
Url=[]
for i in driver.find_elements_by_xpath("//li[@class='o-nav__list-item lrv-u-align-items-center lrv-u-flex']/a"):
    Url.append(i.get_attribute("href"))
Url


driver.get(Url[0])
search_btn=driver.find_element_by_xpath('/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div[1]/div[2]/span/a')
search_btn

search_btn.click()
name=driver.find_elements_by_xpath('//div[@class="chart-results-list // lrv-u-padding-t-150 lrv-u-padding-t-050@mobile-max"]/div/ul/li[4]/ul/li/h3')
len(name)

Song_name=[]
for j in name:
    Song_name.append(j.text)
Song_name

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1001841931.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//li[@class='o-nav__list-item lrv-u-align-items-center lrv-u-flex']/a"):
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1001841931.py:10: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  search_btn=driver.find_element_by_xpath('/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div[1]/div[2]/span/a')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1001841931.py:14: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  name=driver.find_elements_by_xpath('//div[@class="chart-results-list // lrv-u-padding-t-150 lrv-u-padding-t-050@mobile-max"]/div/ul/li[4]/ul/li/h3')

['As It Was',
 'First Class',
 'Heat Waves',
 'Big Energy',
 'Enemy',
 'Stay',
 "Don't Think Jesus",
 'Woman',
 'Super Gremlin',
 'Ghost',
 'Thats What I Want',
 'Bad Habits',
 'abcdefu',
 'Shivers',
 'Cold Heart (PNAU Remix)',
 'Easy On Me',
 'Need To Know',
 'Save Your Tears',
 'One Right Now',
 'In A Minute',
 'Levitating',
 "'Til You Can't",
 'Industry Baby',
 'MAMIII',
 'Bam Bam',
 'Hrs And Hrs',
 "We Don't Talk About Bruno",
 'Right On',
 'Never Say Never',
 "Doin' This",
 'Wasted On You',
 'AA',
 'Good 4 U',
 'Sweetest Pie',
 'Fingers Crossed',
 'I Hate U',
 'Boyfriend',
 'To The Moon!',
 'You Right',
 'Numb Little Bug',
 'Fancy Like',
 'Sand In My Boots',
 'What Happened To Virgil',
 'Pushin P',
 'Beers On Me',
 'The Motto',
 "She's All I Wanna Be",
 "When You're Gone",
 'Buy Dirt',
 'About Damn Time',
 'Shake It',
 'Light Switch',
 'If I Was A Cowboy',
 'Peru',
 'Flowers',
 'Nail Tech',
 'Freaky Deaky',
 '23',
 'Trouble With A Heartbreak',
 'Broadway Girls',
 'Heart On Fire',
 'No Love',
 'Surface Pressure',
 'Slow Down Summer',
 'Flower Shops',
 'Never Wanted To Be That Girl',
 'Me Or Sum',
 'Ahhh Ha',
 'Give Heaven Some Hell',
 'Handsomer',
 'Envolver',
 'Do We Have A Problem?',
 'Get Into It (Yuh)',
 'Rumors',
 'Take My Name',
 'Damn Strait',
 'Circles Around This Town',
 'In My Head',
 'Nobody Like U',
 'Soy El Unico',
 'I Love You So',
 'Come Back As A Country Boy',
 'GINE',
 'City Of Gods',
 'Complete Mess',
 'Leave You Alone',
 'Bones',
 'Banking On Me',
 'She Likes It',
 'Pressure',
 'Desesperados',
 'Over',
 'The Family Madrigal',
 'Hate Our Love',
 'Dos Oruguitas',
 'P Power',
 'Money So Big',
 'Blick Blick!',
 'Fall In Love',
 'X Ultima Vez']

In [28]:
Artist=driver.find_elements_by_xpath('//div[@class="chart-results-list // lrv-u-padding-t-150 lrv-u-padding-t-050@mobile-max"]/div/ul/li[4]/ul/li[1]/span')
len(Artist)

Artist_name=[]
for k in Artist:
    Artist_name.append(k.text)
Artist_name

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/2930564954.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  Artist=driver.find_elements_by_xpath('//div[@class="chart-results-list // lrv-u-padding-t-150 lrv-u-padding-t-050@mobile-max"]/div/ul/li[4]/ul/li[1]/span')

['Harry Styles',
 'Jack Harlow',
 'Glass Animals',
 'Latto',
 'Imagine Dragons X JID',
 'The Kid LAROI & Justin Bieber',
 'Morgan Wallen',
 'Doja Cat',
 'Kodak Black',
 'Justin Bieber',
 'Lil Nas X',
 'Ed Sheeran',
 'GAYLE',
 'Ed Sheeran',
 'Elton John & Dua Lipa',
 'Adele',
 'Doja Cat',
 'The Weeknd & Ariana Grande',
 'Post Malone & The Weeknd',
 'Lil Baby',
 'Dua Lipa',
 'Cody Johnson',
 'Lil Nas X & Jack Harlow',
 'Becky G X Karol G',
 'Camila Cabello Featuring Ed Sheeran',
 'Muni Long',
 'Carolina Gaitan, Mauro Castillo, Adassa, Rhenzy Feliz, Diane Guerrero, Stephanie Beatriz & Encanto Cast',
 'Lil Baby',
 'Cole Swindell / Lainey Wilson',
 'Luke Combs',
 'Morgan Wallen',
 'Walker Hayes',
 'Olivia Rodrigo',
 'Megan Thee Stallion & Dua Lipa',
 'Lauren Spencer-Smith',
 'SZA',
 'Dove Cameron',
 'JNR CHOI & Sam Tompkins',
 'Doja Cat & The Weeknd',
 'Em Beihold',
 'Walker Hayes',
 'Morgan Wallen',
 'Lil Durk Featuring Gunna',
 'Gunna & Future Featuring Young Thug',
 'Dierks Bentley, BRELAND & HARDY',
 'Tiesto & Ava Max',
 'Tate McRae',
 'Shawn Mendes',
 'Jordan Davis Featuring Luke Bryan',
 'Lizzo',
 'Kay Flock, Cardi B, Dougie B & Bory300',
 'Charlie Puth',
 'Miranda Lambert',
 'Fireboy DML & Ed Sheeran',
 'Lauren Spencer-Smith',
 'Jack Harlow',
 'Tyga X Doja Cat',
 'Sam Hunt',
 'Jason Aldean',
 'Lil Durk Featuring Morgan Wallen',
 'Eric Church',
 'Summer Walker & SZA',
 'Jessica Darrow',
 'Thomas Rhett',
 'ERNEST Featuring Morgan Wallen',
 'Carly Pearce & Ashley McBryde',
 'Nardo Wick, Lil Baby & Future',
 'Lil Durk',
 'HARDY',
 'Russ Featuring Ktlyn',
 'Anitta',
 'Nicki Minaj X Lil Baby',
 'Doja Cat',
 'Gucci Mane Featuring Lil Durk',
 'Parmalee',
 'Scotty McCreery',
 'Maren Morris',
 'Lil Tjay',
 "4*TOWN (From Disney And Pixar's Turning Red)",
 'Yahritza y Su Esencia',
 'The Walters',
 'Blake Shelton',
 '6ix9ine',
 'Fivio Foreign, Kanye West & Alicia Keys',
 '5 Seconds Of Summer',
 'Kane Brown',
 'Imagine Dragons',
 'Gunna',
 'Russell Dickerson & Jake Scott',
 'Ari Lennox',
 'Rauw Alejandro & Chencho Corleone',
 'Lucky Daye',
 'Stephanie Beatriz, Olga Merediz & Encanto Cast',
 'Queen Naija & Big Sean',
 'Sebastian Yatra',
 'Gunna Featuring Drake',
 'Yeat',
 'Coi Leray & Nicki Minaj',
 'Bailey Zimmerman',
 'Daddy Yankee & Bad Bunny']

In [29]:
week=driver.find_elements_by_xpath('//div[@class="chart-results-list // lrv-u-padding-t-150 lrv-u-padding-t-050@mobile-max"]/div/ul/li[4]/ul/li[4]/span')
len(week)

Last_week_rank=[]
for k in week:
    Last_week_rank.append(k.text)
Last_week_rank

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3273219041.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  week=driver.find_elements_by_xpath('//div[@class="chart-results-list // lrv-u-padding-t-150 lrv-u-padding-t-050@mobile-max"]/div/ul/li[4]/ul/li[4]/span')

['2',
 '1',
 '3',
 '4',
 '5',
 '6',
 '-',
 '8',
 '7',
 '9',
 '10',
 '12',
 '11',
 '15',
 '16',
 '17',
 '20',
 '23',
 '24',
 '14',
 '21',
 '22',
 '19',
 '30',
 '25',
 '26',
 '18',
 '13',
 '27',
 '31',
 '36',
 '32',
 '28',
 '33',
 '34',
 '29',
 '44',
 '42',
 '37',
 '45',
 '38',
 '48',
 '39',
 '35',
 '41',
 '49',
 '50',
 '52',
 '47',
 '-',
 '-',
 '43',
 '68',
 '53',
 '-',
 '40',
 '60',
 '55',
 '73',
 '58',
 '63',
 '59',
 '56',
 '51',
 '67',
 '65',
 '66',
 '61',
 '76',
 '54',
 '74',
 '70',
 '82',
 '77',
 '80',
 '89',
 '57',
 '64',
 '72',
 '69',
 '86',
 '84',
 '-',
 '71',
 '85',
 '-',
 '94',
 '87',
 '90',
 '92',
 '98',
 '96',
 '78',
 '-',
 '93',
 '91',
 '-',
 '95',
 '-',
 '99']

In [30]:
peak=driver.find_elements_by_xpath('//div[@class="chart-results-list // lrv-u-padding-t-150 lrv-u-padding-t-050@mobile-max"]/div/ul/li[4]/ul/li[5]/span')
len(peak)

Peak_rank=[]
for k in peak:
    Peak_rank.append(k.text)
Peak_rank

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3933072549.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  peak=driver.find_elements_by_xpath('//div[@class="chart-results-list // lrv-u-padding-t-150 lrv-u-padding-t-050@mobile-max"]/div/ul/li[4]/ul/li[5]/span')

['1',
 '1',
 '1',
 '3',
 '5',
 '1',
 '7',
 '8',
 '3',
 '5',
 '8',
 '2',
 '3',
 '4',
 '7',
 '1',
 '8',
 '1',
 '6',
 '14',
 '2',
 '18',
 '1',
 '15',
 '23',
 '16',
 '1',
 '13',
 '27',
 '27',
 '9',
 '32',
 '1',
 '15',
 '19',
 '7',
 '37',
 '38',
 '11',
 '40',
 '3',
 '30',
 '22',
 '7',
 '40',
 '42',
 '44',
 '38',
 '22',
 '50',
 '51',
 '27',
 '53',
 '53',
 '55',
 '18',
 '43',
 '50',
 '59',
 '14',
 '56',
 '13',
 '8',
 '43',
 '64',
 '63',
 '58',
 '18',
 '69',
 '40',
 '70',
 '2',
 '68',
 '51',
 '75',
 '76',
 '52',
 '33',
 '49',
 '20',
 '71',
 '81',
 '83',
 '46',
 '85',
 '86',
 '87',
 '61',
 '86',
 '66',
 '91',
 '77',
 '20',
 '88',
 '36',
 '24',
 '95',
 '37',
 '99',
 '73']

In [31]:
weeks=driver.find_elements_by_xpath('//div[@class="chart-results-list // lrv-u-padding-t-150 lrv-u-padding-t-050@mobile-max"]/div/ul/li[4]/ul/li[6]/span')
len(weeks)

Weeks_on_board=[]
for k in weeks:
    Weeks_on_board.append(k.text)
Weeks_on_board

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/651935275.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  weeks=driver.find_elements_by_xpath('//div[@class="chart-results-list // lrv-u-padding-t-150 lrv-u-padding-t-050@mobile-max"]/div/ul/li[4]/ul/li[6]/span')

['3',
 '2',
 '66',
 '26',
 '22',
 '41',
 '1',
 '38',
 '24',
 '30',
 '31',
 '43',
 '22',
 '32',
 '33',
 '28',
 '45',
 '68',
 '24',
 '2',
 '76',
 '28',
 '39',
 '10',
 '7',
 '17',
 '17',
 '2',
 '14',
 '19',
 '23',
 '15',
 '49',
 '6',
 '16',
 '20',
 '10',
 '8',
 '42',
 '12',
 '44',
 '40',
 '6',
 '15',
 '17',
 '12',
 '11',
 '3',
 '37',
 '1',
 '1',
 '13',
 '12',
 '12',
 '1',
 '9',
 '8',
 '17',
 '5',
 '18',
 '22',
 '16',
 '17',
 '9',
 '13',
 '15',
 '15',
 '9',
 '8',
 '7',
 '4',
 '11',
 '20',
 '12',
 '3',
 '3',
 '15',
 '3',
 '5',
 '4',
 '14',
 '12',
 '1',
 '9',
 '3',
 '1',
 '6',
 '9',
 '5',
 '17',
 '3',
 '5',
 '16',
 '2',
 '16',
 '14',
 '4',
 '4',
 '1',
 '3']

In [32]:
hot=pd.DataFrame()

hot['Song_name']= Song_name
hot['Artist_name ']= Artist_name
hot['Last_week_rank']= Last_week_rank
hot['Peak_rank']= Peak_rank
hot['Weeks_on_board']= Weeks_on_board
hot

,Song_name,Artist_name,Last_week_rank,Peak_rank,Weeks_on_board
0,As It Was,Harry Styles,2,1,3
1,First Class,Jack Harlow,1,1,2
2,Heat Waves,Glass Animals,3,1,66
3,Big Energy,Latto,4,3,26
4,Enemy,Imagine Dragons X JID,5,5,22
...,...,...,...,...,...
95,P Power,Gunna Featuring Drake,91,24,14
96,Money So Big,Yeat,-,95,4
97,Blick Blick!,Coi Leray & Nicki Minaj,95,37,4
98,Fall In Love,Bailey Zimmerman,-,99,1
99,X Ultima Vez,Daddy Yankee & Bad Bunny,99,73,3

7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/

You have to find the following details:

A) Name

B) Designation

C) Company

D) Skills they hire for

E) Location

In [34]:
url='https://www.naukri.com/browse-jobs'
driver.get(url)
Url=[]
for i in driver.find_elements_by_xpath("//ul[@class='midSec menu']/li[2]/a"):
    Url.append(i.get_attribute("href"))
Url

driver.get(Url[0])
search_job=driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input')
search_job

search_job.send_keys('Data Science')
search_btn=driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button')
search_btn

search_btn.click()
name=driver.find_elements_by_xpath('//span[@class="fl ellipsis"]')
len(name)

Name=[]
for j in name:
    Name.append(j.text)
Name

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/2104216734.py:4: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  for i in driver.find_elements_by_xpath("//ul[@class='midSec menu']/li[2]/a"):
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/2104216734.py:9: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  search_job=driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/2104216734.py:13: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  search_btn=driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/2104216734.py:17: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  name=driver.find_elements_by_xpath('//span[@class="fl ellipsis"]')

['Aakash Harit',
 'shravan Kumar Gaddam',
 'MARSIAN Technologies LLP',
 'Anik Agrawal',
 'subhas patel',
 'Abhishek - Only Analytics Hiring - India and',
 'Institute for Financial Management and Resear',
 'Balu Ramesh',
 'Asif Lucknowi',
 'InstaFinancials',
 'Priyanka Akiri',
 'Kalpana Dumpala',
 'Mubarak',
 'Kushal Rastogi',
 'Mahesh Babu Channa',
 'Sakshi Chhikara',
 'Kapil Devang',
 'Ruchi Dhote',
 'Manisha Yadav',
 'Riya Rajesh',
 'Rashmi Bhattacharjee',
 'Faizan Kareem',
 'Rithika dadwal',
 'Sandhya Khandagale',
 'Shaun Rao',
 'Azahar Shaikh',
 'Manas',
 'kumar',
 'Sunil Vedula',
 'Rajat Kumar',
 'Dhruv Dev Dubey',
 'Avodha',
 'Jayanth N',
 'Priya Khare',
 'Ravi Dubey',
 'Amit Sharma',
 'Kanan',
 'Shashikant Chaudhary',
 'Brad',
 'Rutuja Pawar',
 'Madhusudhan Sridhar',
 'Ankit Sinha',
 'Gaurav Chouhan',
 'Rashi Kacker',
 'Ashwini',
 'Balaji Kolli',
 'Rajani Nagaraj',
 'ROHIT Kumar',
 'Amir Chowdhury',
 'SREEDHAR']

In [35]:
des=driver.find_elements_by_xpath('//span[@class="ellipsis clr"]')
len(des)


Designation=[]
for k in des:
    Designation.append(k.text)
Designation

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/67005296.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  des=driver.find_elements_by_xpath('//span[@class="ellipsis clr"]')

['HR Manager',
 'Company Recruiter',
 'Company HR',
 'Company Recruiter',
 'Founder CEO',
 'Recruitment Lead Consultant',
 'Programme Manager',
 'HR Administrator',
 'Director',
 'Human Resource',
 'HR Manager',
 'Executive Hiring',
 'Company HR',
 'Company HR',
 'HR Team Lead',
 'Assistant Manager HR',
 'HR Manager',
 'Senior Executive Talent Acquisition',
 'HR Executive',
 'Manager Talent Acquisition',
 'HR Head',
 'HR MANAGER',
 'HR Recruiter',
 'HR Recruiter',
 'Manager Human Resources',
 'Company Recruiter',
 'Lead Talent acquisition',
 'Proprietor',
 'CEO',
 'Founder CEO',
 'Company Recruitment Head',
 'Business Development Associate',
 'Project Manager',
 'Senior Manager',
 'Recruitment Manager',
 'Consultant',
 'senior technology instructor',
 'HR Recruiter/HR Excutive',
 'Manager, Technical Recruiting',
 'Technical Recruiter',
 'Erp Implementer',
 'Head Analytics',
 'Chief Technical Officer',
 'Sr Product Manager',
 'Director Global Delivery',
 'Co Founder',
 'HR Manager',
 'Architect',
 'Managing Partner',
 'Recruitment Consultant']

In [36]:
comp=driver.find_elements_by_xpath('//p[@class="highlightable"]/a[2]')
len(comp)


Company=[]
for k in comp:
    Company.append(k.text)
Company

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1482848681.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  comp=driver.find_elements_by_xpath('//p[@class="highlightable"]/a[2]')

['Data Science Network',
 'Shore Infotech India Pvt. Ltd',
 'MARSIAN Technologies LLP',
 'Enerlytics Software Solutions Pvt Ltd',
 'LibraryXProject',
 'Apidel Technologies Division of Transpower',
 'IFMR',
 'Techvantage Systems Pvt Ltd',
 'Weupskill- Live Wire India',
 'CBL Data Science Private Limited',
 'Infinitive Software Solutions',
 'Innominds Software',
 'MoneyTap',
 'QuantMagnum Technologies Pvt. Ltd.',
 'SocialPrachar.com',
 'BIZ INFOTECNO PRIVATE LIMITED',
 'BISP Solutions',
 'Bristlecone India Ltd',
 'Easi Tax',
 'Novelworx Digital Solutions',
 'AXESTRACK SOFTWARE SOLUTIONS PRIVATE...',
 'FirstTech Consaltants Pvt.Ltd',
 'Affine Analytics',
 'Compumatrice Multimedia Pvt Ltd',
 'Exela Technologies',
 'NEAL ANALYTICS SERVICES PVT LTD',
 'Autumn Leaf Consulting Services Private...',
 'trainin',
 'Nanoprecise Sci Corp',
 'R.S Consultancy &amp; Services',
 'Confidential',
 'Nikitha Palaparthi',
 'Dollarbird Information Services Pvt, Ltd',
 'Independent Consultant',
 'HyrEzy Talent Solutions LLP',
 'ASCO consulting',
 'NY INST',
 '3D India Staffing Research &amp; Consulting...',
 'O.C. Tanner',
 'Demand Matrix',
 'MADHUSUDHAN SRIDHAR',
 'Suntech Global',
 'Strategic Consulting Lab',
 'Impel Labs Pvt. Ltd.',
 'MRP Advisers',
 'Saras Solutions India Pvt Ltd',
 'WildJasmine',
 'LNT Private Limited',
 'Granular.ai',
 'JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED']

In [37]:
skills=driver.find_elements_by_xpath('//div[@class="hireSec highlightable"]')
len(skills)


Skills=[]
for k in skills:
    Skills.append(k.text)
Skills

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/4286890098.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  skills=driver.find_elements_by_xpath('//div[@class="hireSec highlightable"]')

['Classic ASP Developer, Internet Marketing Professional, Data Science SME, Content Writers, SEO Professional, Revenue Professional',
 '.Net, Java, Data Science, Linux Administration, Sql Server Development, Winforms, Wcf Services, Wpf, Telecom Engineering, Technical Management, Software',
 'Data Science, Artificial Intelligence, Machine Learning, Business Analytics, Deep Learning, statistics, Data Analytics, Data Analysis, support vector machine',
 'Mean Stack, javascript, angularjs, mongodb, Web Services, rest, express, Node.js, Big Data, iot, Data Science, Cloud Computing, saas, Aws',
 'Hadoop, Spark, Digital Strategy, Data Architecture, Command Center, Cdp, Dmp, Kafka, Data Science, Data Analysis, Big Data Analytics, Real Time Analysis, SQL',
 'Analytics, Business Intelligence, Business Analytics, Predictive Modeling, Predictive Analytics, Data Science, Data Analysis, Data Analytics, Big Data, Big',
 'Data Science',
 'Machine Learning, algorithms, Go Getter, Computer Science, spark, Big Data, hdfs, sql, cassandra, hadoop, python, scala, java, Data Science, Front End',
 'Technical Training, Software Development, Presentation Skills, B.tech, M.tech, B.e., mca, msc, Computer Science, freshers, jobs in indore, Data Science, itil',
 'Software Development, It Sales, Account Management, Data Analysis, Customer Service, Sr, Software Engineering, Mvc, Ajax, Asp.net, Html, C#, Javascript',
 'Oracle Dba, Data Science, Data Warehousing, ETL, Jupyter, Numpy, Data Transformation, Snowflake, Teradata, Python, Data Manipulation, Relational Databases',
 'Qa, Ui/ux, Java Developer, Java Architect, C++/qt, Php, Lamp, Api, J2ee, Java, Soa, Esb, Middleware, Bigdata Achitect, Hadoop Architect, Deep',
 'Business Intelligence, Data Warehousing, Data Science, Business Analytics, Customer Support, Business Reporting, Bi',
 'Office Administration, Hr Administration, telecalling, client relationship management, Client Acquisition, Sales, Reception, HR, Recruitment, Onboarding, Human',
 'Social Media, digital media maketing, seo, smm, smo, sem, Content Wirting, social media marketing, social media manager, digital media marketing manager',
 'React.js, Data Science, Java, Front End, Business Analytics, Backend, Tableau, Python, Qa Testing, Automation Testing',
 'Big Data, Hadoop, Data Analytics, Data Science',
 'Qlikview, Qlik Sense, Microsoft Azure, Power Bi, Data Science, Machine Learning',
 'Telecalling, Client Interaction, Marketing, Research, Web Development, Social Media Marketing, Data Entry Operation, Excel, Ms Office, Invoicing',
 'Data Science',
 'Corporate Sales, Software Development, Software Sales, Marketing, Creative Designing, Corporate Planning, Senior Management, Crm, Client Relationship',
 'Data Analytics, Data Science, Machine Learning, Deep Learning, Nlp, Data Mining, Python, R, Database Administration, Text Mining',
 'Data Science, Machine Learning, Python, R, Deep Learning, Big Data, Hadoop',
 'Big Data, Data Science, Artificial Intelligence, Hadoop, Ui Development, Php, Freelancing, .Net, Software Testing, Sap, Leadership Hiring',
 'Java, Net, Angularjs, Hr, Infrastructure, Management, Project Management, Business Analysis, Data Science, Information Technology, Technology',
 'Data Science, Artificial Intelligence, Machine Learning, Data Analytics',
 'Software Architecture, Vp Engineering, Product Management, analytics, Data Science, Node.js, Principal Engineer, Big Data, python, angularjs, React.js',
 'Data Science, Hadoop, Rpas, Devops, Python, Aws, Teaching, Big Data',
 'Signal Processing, Machine Learning, Neural Networks, Data Science, Predictive Analytics, Time Series Analysis, Data Visualization, Technical Leadership, Data',
 'Web Technologies, Project Management, Software Architecture, Data Science, Object Oriented Programming, Computer Science, Electrical Engineering, Architecture',
 'Server Administartion, Verilog, Vhdl, Digital Marketing, Market Research, Property Research, Legal, It And Non It Recruitment, Logistics, Supply Chain, Bfsi',
 'Ethical Hacking, Security Operations Center, SOC, Managed Services, Data Science, Machine Learning, Artificial Intelligence, Operations Research, Education',
 'Data Analytics, Managed Services, Team Leading, python, Machine Learning, Google Analytics, Dmp, Aws, Campaign Analytics, Digital Campaigns, Audience',
 'Data Science, Artificial Intelligence, analytics, Business Intelligence, python, tableau, Power Bi, qlikview, sql, Data Warehousing, Data Visualization',
 'Walmart Interra Skeps Expressstores indifi whitehatJr Practo Zylo Doctalk Medtrail',
 'Machine Learning, Artificial Intelligence, Data Science, Software Engineering, Software Development, Graduate Engineer Trainee, Fresher, Data Analytics, Java',
 'C, C++, Artificial Intelligence, Python, Php, Web Development, Matlab, Data Science, Augmented Reality, C C++',
 'Relationship Management, Retail Sales, Private Banking, Mutual Funds, NISM, Equity, Finance, Financial Products, Financial Services, Verbal, Written',
 'Data Science, Software Engineering',
 'Data Science, Big Data Analytics, Digital Marketing, Content Writing, Ui Development, Database Development, Qa Automation, Python, Project Management',
 'Data Science, Recruitment, Salary',
 'B.Tech, Tableau, Statistics, R, Analytics, Time Series, Data Science, Business Solutions, SQL, Technical Skills, SSAS, SQL Server, Analysis Services, Qlikview',
 'Software Development, Business Intelligence, Big Data Analytics, Database Administration, Data Science, Microsoft Azure, Spark, Cassandra, Object Oriented',
 'Data Science, Node.js, Angularjs',
 'Data Science, Media Marketing, Resource Planning, Managed Services, Display Advertising, Machine Learning, Python, Etl, Sql',
 'Data Analysis, Learning, Data Science, Computer Science, Communication Skills',
 'Java, Hadoop, R, Machine Learning, Spark, Flume, Hdfs, Data Mining, Sas, Big, Data Science, Cloudera, Impala, Bigdata',
 'Software Development, Core Java, Unit Testing, Customer Experience, Problem Solving, Communication Skills, Mysql, Data Science, Sales Management, Analytics',
 'Machine Learning, Data Science, Product Management, New Product, Data Analysis, Computer Vision, Deep Learning, Python, Remote Sensing',
 'Data Science, Machine Learning, Big Data Analytics, Spark, Python, R, Networking, Network Engineering, Placement, Training, Sql, Marketing, Mainframes, All']

In [38]:
loc=driver.find_elements_by_xpath('//p[@class="highlightable"]/span[2]/small')
len(loc)


Location=[]
for k in loc:
    Location.append(k.text)
Location

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3287935566.py:1: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  loc=driver.find_elements_by_xpath('//p[@class="highlightable"]/span[2]/small')

['Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Ahmedabad',
 'UK - (london)',
 'Vadodara / Baroda',
 'Chennai',
 'Trivandrum',
 'Indore',
 'Bengaluru / Bangalore',
 'Hyderabad',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Hyderabad / Secunderabad',
 'Chandigarh',
 'Bhopal',
 'Pune',
 'Navi Mumbai',
 'Cochin',
 'Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Delhi',
 'Bengaluru / Bangalore',
 'Hyderabad / Secunderabad',
 'Mysoru / Mysore',
 'Bengaluru / Bangalore',
 'Ghaziabad',
 'New Delhi',
 'Chennai',
 'Aligarh',
 'Salt Lake City',
 'Pune',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Indore',
 'Bengaluru / Bangalore',
 'MYSORE',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Hyderabad / Secunderabad']

In [41]:
import numpy as np

recruiters=pd.DataFrame()
recruiters['Name']= pd.Series(Name)
recruiters['Designation']=  pd.Series(Designation)
recruiters['Company ']=  pd.Series(Company)
recruiters['Skills they hire for']=  pd.Series(Skills)
recruiters['Location']=  pd.Series(Location)
recruiters

,Name,Designation,Company,Skills they hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
15,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
18,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
19,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
22,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
23,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
24,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
27,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Delhi
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Bengaluru / Bangalore
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Hyderabad / Secunderabad
31,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Mysoru / Mysore
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Bengaluru / Bangalore
33,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Ghaziabad
34,Ravi Dubey,Recruitment Manager,HyrEzy Talent Solutions LLP,Walmart Interra Skeps Expressstores indifi whi...,New Delhi
35,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Chennai
36,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Aligarh
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Salt Lake City
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Pune
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Mumbai
41,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Indore
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Bengaluru / Bangalore
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",MYSORE
44,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Hyderabad / Secunderabad
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Bengaluru / Bangalore
46,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Mumbai
47,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Hyderabad / Secunderabad
48,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",NaN
49,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",NaN

8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/

You have to find the following details:

A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

In [42]:
# Opening Wikipedia webpage
url='https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(url)
time.sleep(1)
# Creating Empty Lists
Book =[]
Author =[]
Volumes_sold =[]
Publisher =[]
Genre =[]
# Scraping Book name
try:
    book=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]')
    for i in book:
        Book.append(i.text)
except NoSuchElementException:
    Book.append('NA')
    
# Scraping Book author's via Xpath
try:
    author=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[3]')
    for i in author:
        Author.append(i.text)
except NoSuchElementException:
    Author.append('NA')
    
# Scraping Volumes sold via Xpath
try:
    sold=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[4]')
    for i in sold:
        Volumes_sold.append(i.text)
except NoSuchElementException:
    Volumes_sold.append('NA')
    
# Scraping publisher via xPath
try:
    publisher=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[5]')
    for i in publisher:
        Publisher.append(i.text)
except NoSuchElementException:
    Publisher.append('NA')
    
# Scraping Genre via Xpath
try:
    genre=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[6]')
    for i in genre:
        Genre.append(i.text)
except NoSuchElementException:
    Genre.append('NA')
#creating dataframe
Top_Books=pd.DataFrame({"Book Title":Book,
                "Author Name":Author,
                'Volumes sold':Volumes_sold,
                'Publisher':Publisher,
                'Genre':Genre})
print('\033[1m'+'Best Selling Books of All Time List by The Guardian  :'+'\033[0m')
Top_Books

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1310252001.py:13: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  book=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1310252001.py:21: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  author=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[3]')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1310252001.py:29: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  sold=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[4]')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1310252001.py:37: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  publisher=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[5]')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/1310252001.py:45: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  genre=driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[6]')

Best Selling Books of All Time List by The Guardian  :

,Book Title,Author Name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

9. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/

You have to find the following details:

A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

In [43]:
# Opening Wikipedia webpage
url='https://www.imdb.com/list/ls095964455/'
driver.get(url)
time.sleep(1)
# Creating Empty List
Name =[]
Year_Span=[]
Genre =[]
Run_Time =[]
Ratings =[]
Votes =[]
# Scraping Name via Xpath
try:
    name=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
    for i in name:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('NA')

# Scraping Year span via Xpath
try:
    year=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
    for i in year:
        Year_Span.append(i.text)
except NoSuchElementException:
    Year_Span.append('NA')
    
# Scraping Genre via Xpath
try:
    genre=driver.find_elements_by_xpath("//span[@class='genre']")
    for i in genre:
        Genre.append(i.text)
except NoSuchElementException:
    Genre.append('NA')
    
# Scraping RunTime via Xpath
try:
    runtime=driver.find_elements_by_xpath("//span[@class='runtime']")
    for i in runtime:
        Run_Time.append(i.text)
except NoSuchElementException:
    Run_Time.append('NA')

# Scraping Ratings via Xpath
try:
    ratings=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
    for i in ratings:
        Ratings.append(i.text)
except NoSuchElementException:
    Ratings.append('NA')

# Scraping Votes via Xpath
try:
    votes=driver.find_elements_by_xpath("//span[@name='nv']")
    for i in votes:
        Votes.append(i.text)
except NoSuchElementException:
    Votes.append('NA')
#creating dataframe
IMDB_TV=pd.DataFrame({"Name":Name,
                "Year Span":Year_Span,
                "Genre":Genre,
                "Run Time":Run_Time,
                "Ratings":Ratings,
                "Votes":Votes})
print('\033[1m'+'Top 100 most watched tv shows of all time IMDB :'+'\033[0m')
IMDB_TV

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3651252677.py:14: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  name=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3651252677.py:22: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  year=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3651252677.py:30: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  genre=driver.find_elements_by_xpath("//span[@class='genre']")
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3651252677.py:38: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  runtime=driver.find_elements_by_xpath("//span[@class='runtime']")
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3651252677.py:46: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  ratings=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/3651252677.py:54: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  votes=driver.find_elements_by_xpath("//span[@name='nv']")

Top 100 most watched tv shows of all time IMDB :

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,980,423"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"986,137"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"943,860"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"281,968"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"241,882"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.4,"48,534"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"59,169"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"188,785"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"40,009"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"226,276"

10. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/

You have to find the following details:

A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

In [46]:
# Opening Wikipedia webpage
url='https://archive.ics.uci.edu/'
driver.get(url)
time.sleep(1)
# Clicking on all datasets links
dataset=driver.find_element_by_xpath("//a[@href='datasets.php']")
dataset.click()
time.sleep(1)
# Creating empty lists
Dataset =[]
Data_Type =[]
Task =[]
Attribute_Type =[]
No_of_Instances =[]
No_of_Attribute =[]
Year =[]
# Scraping DataSet Name via Xpath
from tqdm import tqdm
try:
    dataset=driver.find_elements_by_xpath("//p[@class='normal']/b/a")
    for i in tqdm(dataset):
        Dataset.append(i.text)
        time.sleep(0.15)
except NoSuchElementException:
    Dataset.append('NA')
    
# Scraping Data Type via Xpath
try:
    Type=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]')
    for i in Type[1:]:
        Data_Type.append(i.text)
except NoSuchElementException:
    Data_Type.append('NA')
    
# Scraping Task via Xpath
try:
    task=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]')
    for i in task[1:]:
        Task.append(i.text)
except NoSuchElementException:
    Task.append('NA')
    
# Scraping Attribute_Type via Xpath
try:
    attribute_Type=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]')
    for i in attribute_Type[1:]:
        Attribute_Type.append(i.text)
except NoSuchElementException:
    Attribute_Type.append('NA')
    
# Scraping No_of_Instances via Xpath
try:
    no_of_Instances=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]')
    for i in no_of_Instances[1:]:
        No_of_Instances.append(i.text)
except NoSuchElementException:
    No_of_Instances.append('NA')

# Scraping No_of_Attribute via Xpath
try:
    no_of_Attribute=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]')
    for i in no_of_Attribute[1:]:
        No_of_Attribute.append(i.text)
except NoSuchElementException:
    No_of_Attribute.append('NA')
    
# Scraping Year via Xpath
try:
    year=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]')
    for i in year[1:]:
        Year.append(i.text)
except NoSuchElementException:
    Year.append('NA')
    
    


# Creating Data Frame for UCI Dataset
import numpy as np
UCI_Dataset=pd.DataFrame({'DataSet Title':pd.Series(Dataset),
                'Data Type':pd.Series(Data_Type),
                'Task':pd.Series(Task),
                'Attribute Type':pd.Series(Attribute_Type),
                'No of Instances':pd.Series(No_of_Instances),
                'No of Attribute':pd.Series(No_of_Attribute),
                'Year':pd.Series(Year)})
print('\033[1m'+' UCI Machine Learning Dataset:'+'\033[0m')
UCI_Dataset

C:\Users\USER\AppData\Local\Temp/ipykernel_7940/538388220.py:6: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  dataset=driver.find_element_by_xpath("//a[@href='datasets.php']")
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/538388220.py:20: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  dataset=driver.find_elements_by_xpath("//p[@class='normal']/b/a")
100%|████████████████████████████████████████████████████████████████████████████████| 622/622 [02:11<00:00,  4.71it/s]
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/538388220.py:29: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  Type=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/538388220.py:37: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  task=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/538388220.py:45: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  attribute_Type=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/538388220.py:53: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  no_of_Instances=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/538388220.py:61: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  no_of_Attribute=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]')
C:\Users\USER\AppData\Local\Temp/ipykernel_7940/538388220.py:69: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  year=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]')

 UCI Machine Learning Dataset:

,DataSet Title,Data Type,Task,Attribute Type,No of Instances,No of Attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021